[RFR] Feat two players
marmelab/quoridor-python pull request #7
Opened 2019-06-17 15:29 UTC by mchaffotte

![TwoPlayers](https://user-images.githubusercontent.com/4921926/59616829-7b4d6d00-9125-11e9-8743-f863b89ec34d.gif)

2019-06-17 15:57 UTC, Kmaschta commented on src/game.py
> +        player_turn = 1
Argument is directly updated. This might cause a side effect.

2019-06-17 15:57 UTC, Kmaschta commented on src/game.py
> +        victory = pawn.x == 0
Argument is directly updated. This might cause a side effect.

2019-06-17 15:57 UTC, Kmaschta commented on src/console.py
> +    key = prompt("Player #" + str(player_number) + ": Where do you want to move the pawn? ")
fstrings! :p
(not mandatory)

2019-06-17 15:57 UTC, Kmaschta commented on src/game.py
> +    new_pawns = pawns
Be aware: you didn't copied the value of your pawns, you just stored the reference of your pawns.
So, if you change new_pawns later, pawns will be changed too

2019-06-17 15:57 UTC, Kmaschta commented on src/game.py
> +                new_pawns = deepcopy(new_pawns)
I'd recommend to deepcopy `pawns` at start, and then update new_pawns as you need

2019-06-17 16:18 UTC, ThieryMichel requested changes

2019-06-17 16:18 UTC, ThieryMichel commented on src/board.py
> +    item = None
```py
return Item.PAWN_1 if index == 0 else Item.PAWN_2
```

2019-06-18 08:01 UTC, ThieryMichel requested changes

2019-06-18 08:01 UTC, ThieryMichel commented on src/game.py
>      if player_turn + 1 > len(pawns):
return 1 if player_turn + 1 > len(pawns) else player_turn + 1

2019-06-18 09:30 UTC, merged